### ISSUE TITLE
Mailchimp automation doc recover

### ISSUE THREAD

**Issue by Udesly** [eclipsesrl/udesly-docs#5]
emmu pers a doc e mailchimp automation

**Comment by eclipsesrl** [comment]
Old Doc

<h2>How to install and use Mailchimp Automation plugin for EDD and RCP</h2>
<p class="p1"><span class="s1">Go to the WordPress admin panel and go to the “plugins” menu. Click on the “add new” button on the top and then upload the plugin.</span></p>
<p class="p1"><span class="s1">Select the udesly-mailchimp-automation.zip file from the plugin folder and then click on the “install now” button. Wait for the installation and then activate the plugin.</span></p>
<p class="p1">
&nbsp;
<h3><strong>Preliminary Remarks</strong></h3>
This plugin allows to create automations for EDD e-commerce platforms, so you have it hooked up to Mailchimp and standard automations working with native WordPress hooks.

Also, a pre-configuration for RCP is available.

&nbsp;
<h3>Plugin Panel</h3>
<strong>Automations</strong>

This section allows to create and handle all the automations you want to implement between EDD and Mailchip. Take a look <a href="https://mailchimp.com/resources/mailchimp-e-commerce/" target="_blank" rel="noopener">here</a> to see how to connect your store to Mailchimp.

Can choose between pre-configurated or custom automations. Pre-configurated ones consists in a list of triggers corresponding to a certain action that the user makes in the store (complete a payment, add to cart, remove from cart, etc.). Also, some triggers for RCP are pre-configurated.


Custom automations permits to insert other hooks made available by WordPress or any other plugin installed.

&nbsp;

<strong>Settings</strong>

Here Mailchimp API and Data center must be inserted. If you have trouble creating your API, take a look at this <a href="https://mailchimp.com/help/about-api-keys/" target="_blank" rel="noopener">guide</a>.


&nbsp;

<strong>Ecommerce</strong>

This section contains data necessary to hook EDD to Mailchimp.

The Sync button is very important. By clicking on it, you'll be able to synchronize EDD products and bring them on Mailchimp and create dynamic campaigns.

<strong>Abandoned Cart</strong>

The plugin registers the carts abandoned by users on EDD and, once a day, sends them to Mailchimp which will do a specific action based on a specific configurations set by the user.

This function can be paused.

**Comment by Udesly** [comment]
done
