### ISSUE TITLE
X to Webflow doc recover

### ISSUE THREAD

**Issue by Udesly** [eclipsesrl/udesly-docs#6]

**Comment by eclipsesrl** [comment]
Shopify CSV

<h2>How it works</h2>
<div class="div-block-244">
<p class="paragraph-54">Go to the "products" menu from your Shopify panel and click on the "export" button.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Install and launch the Udesly App (MacOS and Windows), import the Shopify CSV to start the conversion.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Once you have the converted CSV file you are ready to import the products in Webflow.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Go to Webflow, open the e-commerce menu from your designer and click on the products menu. On the top right you can find the "Import" button. Drag the CSV you have exported from the plugin, and the work is done!</p>
&nbsp;

</div>
<div class="videoYouTubeWrapper"><iframe src="https://www.youtube.com/embed/7n2CopKanBI" width="700" height="393" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>


Squarespace

<h2>How it works</h2>
<div class="div-block-244">
<p class="paragraph-54">Go to settings &gt;&gt; advanced &gt;&gt;import/export. Click on the "export" button and choose to download a CSV file of your products.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Install and launch the Udesly App (MacOS and Windows), import the Squarespace CSV to start the conversion.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Once you have the converted CSV file you are ready to import the products in Webflow.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Go to Webflow, open the e-commerce menu from your designer and click on the products menu. On the top right you can find the "Import" button. Drag the CSV you have exported from the plugin, and the work is done!</p>
&nbsp;

</div>
<div class="videoYouTubeWrapper"><iframe src="https://www.youtube.com/embed/R8NoqLNq8Tk" width="700" height="393" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

Wix

<h2>How it works</h2>
<div class="div-block-244">
<p class="paragraph-54">Go to the "products" menu from your Wix panel and click on the "export" button.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Install and launch the Udesly App (MacOS and Windows), import the Wix CSV to start the conversion.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Once you have the converted CSV file you are ready to import the products in Webflow.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Go to Webflow, open the e-commerce menu from your designer and click on the products menu. On the top right you can find the "Import" button. Drag the CSV you have exported from the plugin, and the work is done!</p>
&nbsp;

</div>
<div class="videoYouTubeWrapper"><iframe src="https://www.youtube.com/embed/UT7wqI5_r-U" width="700" height="393" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

Big Commerce

<div class="div-block-244">
<h2>How it works</h2>
<p class="paragraph-54">Go to products &gt;&gt; export. Click on the "export" button and export your products as CSV.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Install and launch the Udesly App (MacOS and Windows), import the BigCommerce CSV to start the conversion.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Once you have the converted CSV file you are ready to import the products in Webflow.</p>

</div>
<div class="div-block-244">
<p class="paragraph-54">Go to Webflow, open the e-commerce menu from your designer and click on the products menu. On the top right you can find the "Import" button. Drag the CSV you have exported from the plugin, and the work is done!</p>

</div>
<div class="videoYouTubeWrapper"><iframe src="https://www.youtube.com/embed/g7qwyOUS3Yk" width="700" height="393" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

**Comment by Udesly** [comment]
done
